-- MySQL Script generated by MySQL Workbench
-- Thu Dec  7 23:52:09 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_kursach_7
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_kursach_7
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_kursach_7` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `db_kursach_7` ;

-- -----------------------------------------------------
-- Table `db_kursach_7`.`firm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_kursach_7`.`firm` (
  `id_firm` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL DEFAULT NULL,
  `field` VARCHAR(45) NULL DEFAULT NULL,
  `year` INT NULL DEFAULT NULL,
  `website` VARCHAR(45) NULL DEFAULT NULL,
  `director` VARCHAR(105) NULL DEFAULT NULL,
  `work_phone` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_firm`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_kursach_7`.`recruter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_kursach_7`.`recruter` (
  `id_recruter` INT NOT NULL AUTO_INCREMENT,
  `specialization` VARCHAR(45) NULL DEFAULT NULL,
  `numberOfHires` INT NULL DEFAULT NULL,
  `portfolio` VARCHAR(45) NULL DEFAULT NULL,
  `search_speciafication` VARCHAR(45) NULL DEFAULT NULL,
  `id_users` INT NOT NULL ,
  `id_firm` INT NOT NULL,
  `users_id_users` INT NOT NULL,
  PRIMARY KEY (`id_recruter`),
  INDEX `R_s_idx` (`id_users` ASC) VISIBLE,
  INDEX `r_f_idx` (`id_firm` ASC) VISIBLE,
  INDEX `fk_recruter_users1_idx` (`users_id_users` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_kursach_7`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_kursach_7`.`role` (
  `id_role` INT NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_role`))
ENGINE = MyISAM
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_kursach_7`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_kursach_7`.`user_role` (
  `id_user` INT NOT NULL,
  `id_role` INT NOT NULL,
  PRIMARY KEY (`id_user`, `id_role`),
  INDEX `FK2aam9nt2tv8vcfymi3jo9c314` (`id_role` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_kursach_7`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_kursach_7`.`users` (
  `id_users` INT NOT NULL AUTO_INCREMENT,
  `active` BIT(1) NULL DEFAULT NULL,
  `age` VARCHAR(255) NULL DEFAULT NULL,
  `bio` VARCHAR(255) NULL DEFAULT NULL,
  `first_name` VARCHAR(255) NULL DEFAULT NULL,
  `last_name` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(255) NULL DEFAULT NULL,
  `username` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_users`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_kursach_7`.`vacancy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_kursach_7`.`vacancy` (
  `id_vacancy` INT NOT NULL AUTO_INCREMENT,
  `position` VARCHAR(45) NULL DEFAULT NULL,
  `salary` DOUBLE NULL DEFAULT NULL,
  `responsibilities` VARCHAR(255) NULL DEFAULT NULL,
  `requirements` VARCHAR(255) NULL DEFAULT NULL,
  `conditions` VARCHAR(255) NULL DEFAULT NULL,
  `keySkills` VARCHAR(105) NULL DEFAULT NULL,
  `date_of_create` DATETIME NULL DEFAULT NULL,
  `firm_id_firm` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_vacancy`),
  INDEX `FKj80ns9l9xycq7lks0ufe6riuy` (`firm_id_firm` ASC) VISIBLE,
  CONSTRAINT `FKj80ns9l9xycq7lks0ufe6riuy`
    FOREIGN KEY (`firm_id_firm`)
    REFERENCES `db_kursach_7`.`firm` (`id_firm`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
