spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mobilefarm?useSSL=true
    username: root
    password: 12345
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect:
          org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  mail:
    host: mail.vkhp.by
    port: 25
    username: anna-mihalevich@vkhp.by
    password: 7AQNa~jD|E1R7
    properties:
      mail:
        smtp:
          auth=true:
          starttls:
            enable=true:logging:
  level:
    org.springframework: INFO
    by.netcracker: ERROR
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
server:
  port: 8088

